"""empty message

Revision ID: 459fadb80120
Revises: 
Create Date: 2022-04-30 03:27:32.186440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459fadb80120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('circumference', sa.Integer(), nullable=True),
    sa.Column('length_of_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
